server:
  port: 8000
  compression:
    enabled: true
  tomcat:
    accesslog:
      directory: ./logs
      enabled: false
      prefix: access_log
    accept-count: 500
    max-threads: 600
    min-spare-threads: 50
  undertow:
    accesslog:
      dir: ./logs
      enabled: true
      prefix: access_log.
  session:
    timeout: 1500
    persistent: false


spring:
  profiles:
    active: develop
  data:
    mongodb:
      uri: mongodb://conference_91:b1cdfd980f0af6e50963@172.20.31.21:27017,172.20.31.22:27017,172.20.31.23:27017/conference
  redis:
    database: 0
    host: 172.20.31.5
    port: 6380
    password: X8l9GV7YJBtEgB9Z3ET8
    timeout: 3000
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      fileSizeThreshold: 200MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:./dist/
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: messages